---
abstract: 'Flexible ways to match a string'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: String-FlexMatch
provides:
  String::FlexMatch:
    file: lib/String/FlexMatch.pm
    version: 1.100820
  String::FlexMatch::Test:
    file: lib/String/FlexMatch/Test.pm
    version: 1.100820
requires:
  Carp: 0
  Class::Accessor::Complex: 0
  English: 0
  Exporter: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::Builder: 0
  Test::More: 0.88
  YAML: 0
  overload: 0
  parent: 0
  perl: 5.008
  vars: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=String-FlexMatch
  homepage: http://search.cpan.org/dist/String-FlexMatch/
  repository: http://github.com/hanekomu/String-Flexmatch
version: 1.100820
