---
abstract: 'Flexible ways to match a string'
author:
  - 'Marcel GrE<uuml>nauer, C<< <marcel@cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.70
  YAML: 0.65
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: String-FlexMatch
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Class::Accessor::Complex: 0.12
  perl: 5.6.0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=String-FlexMatch
  homepage: http://search.cpan.org/dist/String-FlexMatch/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/hanekomu/string-flexmatch.git
version: 0.13
